name: rs
channels:
    - conda-forge
    - defaults
dependencies:
    - python=3.10
    - ffmpeg=6.1.1
    - gcc=12.1.0
    - pip=23.2.1
    - pip:
          - opencv-python==4.9.0.80
          - pyyaml==6.0.1
          - Pillow==10.3.0
